server:
  port: 9090

spring:
  profiles:
    group:
      local: local
      prod: prod
  redis:
    host: 127.0.0.1
    port: 6379
    prefix: "bus"
    database: 0

---
spring:
  config:
    activate:
      on-profile: local
  cloud:
    gcp:
      credentials:
        location: 'file:src/main/resources/xxx.json'
      project-id: 'xxx-web-services'
      topic: 'bus-0-ping'
  redis:
    daum:
      host: 127.0.0.1
      port: 6379
    naver:
      host: 127.0.0.1
      port: 6379
    google:
      host: 127.0.0.1
      port: 6379
    nate:
      host: 127.0.0.1
      port: 6379
  tasks:
    ping: 'https://XXX.a.run.app/.ping'

---
spring:
  config:
    activate:
      on-profile: prod
  cloud:
    gcp:
      credentials:
        location: 'classpath:/xxx.json'
      project-id: 'xxx-web-services'
      topic: 'bus-0-ping'
  redis:
    daum:
      host: 127.0.0.1
      port: 6379
    naver:
      host: 127.0.0.1
      port: 6379
    google:
      host: 127.0.0.1
      port: 6379