name: kotlin lint

on:
    pull_request:
        paths:
            - "**/*.kt"
            - ".github/workflows/callback-lint.yml"

    jobs:
        ktlint:
            runs-on: ubuntu-latest

            steps:
                - name: "checkout"
                  uses: actions/checkout@v2

                - name: "kotlin lint"
                  uses: "vroy/gha-kotlin-linter@v1"
